const db = require("../db");
const { calculateForecast } = require("./forecastingService");

async function generatePONumber(dateStr) {
  const dateObj = new Date(dateStr);
  const formattedDate = dateObj.toISOString().slice(0, 10).replace(/-/g, "");
  const [{ count }] = await db("purchase_orders").where("date", dateStr).count("id as count");
  const seq = parseInt(count || 0) + 1;
  const seqStr = String(seq).padStart(4, "0");
  return `PO-${formattedDate}-${seqStr}`;
}

async function runAutoPoDrafting() {
  const forecasts = await calculateForecast();
  const forecastMap = new Map(forecasts.map(f => [f.item_code, f]));

  const reorderPoints = await db("reorder_points").where("is_active", true);
  const stockLevels = await db("stock")
    .select("item_code")
    .sum("remaining as remaining")
    .groupBy("item_code");

  const stockMap = new Map(stockLevels.map(s => [s.item_code, parseFloat(s.remaining || 0)]));

  // Supplier group -> items to order
  const draftPoGroups = {};

  for (const rp of reorderPoints) {
    const currentStock = stockMap.get(rp.item_code) || 0;
    const forecast = forecastMap.get(rp.item_code);
    const neededForecast = forecast ? forecast.forecasted_3day_need : 0;

    // Check if stock is low
    if (currentStock <= rp.min_qty || currentStock < neededForecast) {
      // Order amount is max of reorder_qty or shortfall
      const shortfall = Math.max(0, Math.max(rp.reorder_qty, neededForecast - currentStock));
      if (shortfall <= 0) continue;

      // Find supplier: check quotes first to find cheapest
      const bestQuote = await db("supplier_rate_quotes")
        .where("item_code", rp.item_code)
        .orderBy("quoted_rate", "asc")
        .first();

      let supplierId = rp.preferred_supplier_id;
      let unitPrice = 0.0;
      
      if (bestQuote) {
        supplierId = bestQuote.supplier_id || rp.preferred_supplier_id;
        unitPrice = parseFloat(bestQuote.quoted_rate);
      }

      if (!supplierId) {
        // Find any active supplier as fallback
        const fallbackSupplier = await db("suppliers").first();
        if (fallbackSupplier) supplierId = fallbackSupplier.id;
        else continue;
      }

      const supplier = await db("suppliers").where("id", supplierId).first();
      if (!supplier) continue;

      // Fetch fallback unit price if not in quote
      if (unitPrice === 0.0) {
        const latestStock = await db("stock")
          .where("item_code", rp.item_code)
          .orderBy("date", "desc")
          .first();
        unitPrice = latestStock ? parseFloat(latestStock.price) : 10.0; // fallback default price
      }

      const unit = forecast ? forecast.unit : "units";

      if (!draftPoGroups[supplierId]) {
        draftPoGroups[supplierId] = {
          supplier_id: supplierId,
          supplier_name: supplier.name,
          items: []
        };
      }

      draftPoGroups[supplierId].items.push({
        item_code: rp.item_code,
        name: rp.name,
        qty: shortfall,
        unit,
        unit_price: unitPrice,
        total_price: shortfall * unitPrice
      });
    }
  }

  const createdDrafts = [];
  const todayStr = new Date().toISOString().slice(0, 10);

  // Write draft POs into database
  for (const supplierId of Object.keys(draftPoGroups)) {
    const group = draftPoGroups[supplierId];
    const total_amount = group.items.reduce((sum, it) => sum + it.total_price, 0);
    const po_number = await generatePONumber(todayStr);

    const draftPO = await db.transaction(async (trx) => {
      const [po] = await trx("purchase_orders")
        .insert({
          po_number,
          supplier_id: parseInt(supplierId),
          date: todayStr,
          status: "Draft",
          total_amount,
          notes: "Auto-generated by forecasting and reorder engine."
        })
        .returning("*");

      const itemsToInsert = group.items.map(it => ({ ...it, po_id: po.id }));
      const savedItems = await trx("purchase_order_items").insert(itemsToInsert).returning("*");
      return { ...po, items: savedItems };
    });

    createdDrafts.push(draftPO);
  }

  return createdDrafts;
}

module.exports = { runAutoPoDrafting };
